name: MERN Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{ steps.filter.outputs.client }}
      server_changed: ${{ steps.filter.outputs.server }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            client:
              - 'client/**'
            server:
              - 'server/**'

  build_client:
    needs: detect_changes
    if: needs.detect_changes.outputs.client_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & Push Client Image
        run: |
          docker build -t dema/thread-client ./client
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push dema/thread-client

      - name: Deploy Client to VPS
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
            cd /root/app &&
            docker pull dema/thread-client &&
            docker compose up -d --no-deps client
          "

  build_server:
    needs: detect_changes
    if: needs.detect_changes.outputs.server_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & Push Server Image
        run: |
          docker build -t dema/thread-server ./server
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push dema/thread-server

      - name: Deploy Server to VPS
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
            cd /root/app &&
            docker pull dema/thread-server &&
            docker compose up -d --no-deps server
          "
