name: MERN Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & Push Client Image
        run: |
          docker build -t gdfa95713/thread-client ./client
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push gdfa95713/thread-client

      - name: Build & Push Server Image
        run: |
          docker build -t gdfa95713/thread-server ./server
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push gdfa95713/thread-server

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/app
            docker pull gdfa95713/thread-client
            docker pull gdfa95713/thread-server
            docker compose up -d
